jobs:
    main:
        requires: [~commit, ~pr]
        image: node:12
        steps:
            - echo: echo
    build-node8:
        image: node:8
        steps: 
            - init: npm install
            - test: npm test
            - publish: |
                echo "publishing against node 8"
                meta set publish.node8 `date +%s`
        requires: [main]
        
    # B and C will run in parallel
    build-node10:
        image: node:10
        steps:
            - init: npm install
            - test: npm test
            - publish: |
                echo "publishing against node 10"
                meta set publish.node10 `date +%s`
        requires: [main]
    delploy-stage:  
        image: node:10
        steps:
            - verify: echo verify
            - deploy-8: echo "deploying node8 $(meta get publish.node8)"
            - deploy-10: echo "deploying node10 $(meta get publish.node10)"
        requires: [build-node10, build-node8]
    delploy-prod:  
        image: node:10
        steps:
            - verify: echo verify
            - deploy-8: echo "deploying node8 $(meta get publish.node8)"
            - deploy-10: echo "deploying node10 $(meta get publish.node10)"
        requires: [delploy-stage]
    rollback-prod:
        image: node:10
        steps:
            - rollback-8: |
                echo "rolling back to version $(meta get publish.node8)"
            - rollback-10: |
                echo "rolling back to version $(meta get publish.node10)"
